### ISSUE TITLE
项目里依赖的 gcanvas 是哪里来的?

### ISSUE THREAD

**Issue by signer** [weex-plugins/weex-plugin-gcanvas#1]
是阿里的内部库吗?
我用 weexpack 添加 gcanvas 后, pod install 出错:

➜  Weexplugin  pod install
Analyzing dependencies
[!] Unable to find a specification for `GCanvas`

**Comment by signer** [comment]
@littleseven 这个 gcanvas 能开源吗?

**Comment by jwxbond** [comment]
GCanvas 暂时还是二进制库发布，后续会考虑开源
